server:
  port: 9004


spring:
  application:
    name: nacos-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf65ewl375287v916.mysql.rds.aliyuncs.com:3306/demo?useUnicode=true&amp;characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: jdwhy
    password: Prejd_2017
  cloud:
    nacos:
      discovery:
       server-addr: 127.0.0.1:8848


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xch.com.xch.springcloud.entities


management:
  endpoints:
    web:
      exposure:
        include: "*"


